---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: build
  # image: golang
  commands:
  - echo "Building ..."
  - go build -o release/dronedemo cmd/dronedemo/*.go
