---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: node:10.17-alpine
  commands:
  - npm i
- name: build
  image: golang:1.13-alpine
  commands:
  - go build
  # - echo "Building ..."
  # - go build -o release/dronedemo cmd/dronedemo/*.go
